stages:
  plot_signals:
    cmd: python src\create_plots.py
    deps:
    - data\correct_recordings.txt
    - data\eda_anon.pkl
    - src\create_plots.py
    outs:
    - plots\input_signals\
  compute_histograms:
    cmd: python src\compute_histograms.py
    deps:
      - data\eda_anon.pkl
      - src\compute_histograms.py
    outs:
      - data\histograms.csv
